version: 2.1

executors:
  terraenv_build_release:
    docker:
      - image: centos:7
    working_directory: ~/repo

commands:
  terraenv_build_release:
    steps:
      - checkout
      - run:
          name: 'Install Packages'
          command: |
              yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
              yum update -y && \
              yum install -y python36u python36u-libs python36u-devel python36u-pip git make && \
              wget https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz . && \
              tar xvzf ghr_v0.13.0_linux_amd64.tar.gz && cd ghr_v0.13.0_linux_amd64 && \
              chmod +x ghr && mv ghr /usr/local/bin && \
              pip3.6 install -r requirements.txt 
      - run:
          name: 'Create Build'
          command: |
              make build build-pip
              make package
      - run:
          name: 'Publish Build'
          command: |
              LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
              ghr $LATEST_TAG dist/terraenv_linux_x64.tar.gz && \ 
              VERSION=$LATEST_TAG make upload-pip

jobs:
  terraenv_build_release:
    executor: terraenv_build_release
    steps:
      - terraenv_build_release

workflows:
  terraenv_build_release:
    jobs:
      - terraenv_build_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
